// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt70tzYIVnxnCM-Kf5RNjs-cI9Jy85Vv4',
    appId: '1:582653690490:web:00d2eeb314b6d34d3c71c3',
    messagingSenderId: '582653690490',
    projectId: 'fir-27c3f',
    authDomain: 'fir-27c3f.firebaseapp.com',
    databaseURL: 'https://fir-27c3f-default-rtdb.firebaseio.com',
    storageBucket: 'fir-27c3f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2nkyqXdGy-yo8xLM7XO_OQhGgolljXjg',
    appId: '1:582653690490:android:58a79a85ce599af73c71c3',
    messagingSenderId: '582653690490',
    projectId: 'fir-27c3f',
    databaseURL: 'https://fir-27c3f-default-rtdb.firebaseio.com',
    storageBucket: 'fir-27c3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5_B3zT4QKaa9iSQD79SdHYvSl9i7VUQI',
    appId: '1:582653690490:ios:0d3f631a59defbb23c71c3',
    messagingSenderId: '582653690490',
    projectId: 'fir-27c3f',
    databaseURL: 'https://fir-27c3f-default-rtdb.firebaseio.com',
    storageBucket: 'fir-27c3f.appspot.com',
    androidClientId: '582653690490-d0dbdrcv3l0kfib06p23jk4jhorechip.apps.googleusercontent.com',
    iosClientId: '582653690490-8c7lsl2s0dl6bcf9hnlrrr17qh0a2n5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginRegisterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5_B3zT4QKaa9iSQD79SdHYvSl9i7VUQI',
    appId: '1:582653690490:ios:0d3f631a59defbb23c71c3',
    messagingSenderId: '582653690490',
    projectId: 'fir-27c3f',
    databaseURL: 'https://fir-27c3f-default-rtdb.firebaseio.com',
    storageBucket: 'fir-27c3f.appspot.com',
    androidClientId: '582653690490-d0dbdrcv3l0kfib06p23jk4jhorechip.apps.googleusercontent.com',
    iosClientId: '582653690490-8c7lsl2s0dl6bcf9hnlrrr17qh0a2n5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginRegisterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt70tzYIVnxnCM-Kf5RNjs-cI9Jy85Vv4',
    appId: '1:582653690490:web:8c864c2b77892fc23c71c3',
    messagingSenderId: '582653690490',
    projectId: 'fir-27c3f',
    authDomain: 'fir-27c3f.firebaseapp.com',
    databaseURL: 'https://fir-27c3f-default-rtdb.firebaseio.com',
    storageBucket: 'fir-27c3f.appspot.com',
  );
}
